### ISSUE TITLE
Error when used with Django CMS 3.6

### ISSUE THREAD

**Issue by emanresu92** [misli/django-cms-articles#2]
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/data/djangocms/lib/python3.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/data/djangocms/lib/python3.7/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/data/djangocms/lib/python3.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/data/djangocms/lib/python3.7/site-packages/django/apps/registry.py", line 116, in populate
    app_config.ready()
  File "/data/djangocms/lib/python3.7/site-packages/cms_articles/apps.py", line 10, in ready
    from . import signals
  File "/data/djangocms/lib/python3.7/site-packages/cms_articles/signals/__init__.py", line 10, in <module>
    from .plugins import post_reorder_plugins, pre_delete_plugins, pre_save_plugins
  File "/data/djangocms/lib/python3.7/site-packages/cms_articles/signals/plugins.py", line 3, in <module>
    from cms.signals.plugins import get_placeholder
ModuleNotFoundError: No module named 'cms.signals.plugins'

**Comment by misli** [comment]
Hi Eman, thank You for Your report. I know about it and I'd like to fix it soon. There may however be some more things to do support django CMS 3.6. I'll notify You here once it is ready.

**Comment by misli** [comment]
django CMS 3.6 is supported in version 1.3.
